resources:
- name: input
  type: git
  icon: git
  source:
    uri: https://github.com/continental/jenkins_plugin_joblogger.git
    branch: master
  check_every: 60s

- name: resource-src
  type: git
  icon: git
  source:
    uri: https://github.com/smichard/s3_demo.git
    branch: master
  check_every: 60s

- name: minio-target
  type: s3
  icon: database
  source:
    endpoint: http://192.168.178.49:9000
    bucket: releases
    regexp: release_history/(.*)-(.*).tar.gz
    access_key_id: admin
    secret_access_key: admin123

- name: ecs-target
  type: s3
  icon: cloud-upload
  source:
    endpoint: ((ecs_endpoint))
    bucket: releases
    regexp: release_history/(.*)-(.*).tar.gz
    access_key_id: ((ecs_key))
    secret_access_key: ((ecs_secret))

jobs:
- name: push-to-minIO
  plan:
    - get: input
      trigger: false
    - get: resource-src
      trigger: false
    - task: create-backup
      file: resource-src/ci/save_to_storage.yml
      params:
        NAME: app-code
    - put: minio-target
      params:
        file: ./file/*-*.tar.gz
        acl: public-read

- name: push-to-ECS
  plan:
    - get: input
      trigger: false
    - get: resource-src
      trigger: false
    - task: create-backup
      file: resource-src/ci/save_to_storage.yml
      params:
        NAME: app-code
    - put: ecs-target
      params:
        file: ./file/*-*.tar.gz
        acl: public-read